### ISSUE TITLE
Admin guide issues

### ISSUE THREAD

**Issue by jhahkala** [TrustworthyFactory/factory#1]
1. The admin guide says that the easiest way to install the trustworthy factory is to "recover the Zip archive and unzip it" but it doesn't say from where. I ahven't found it anywhere.
2. On the readme.md it says "To access this GE, please, refer to the FiWARE catalogue http://catalogue.fiware.org/enablers/trustworthy-factory" clicking on the link gives "Access denied" page. Searching the FIWARE catalogue for "trust", "trustworthy" or "trustworthy factory" doesn't give any hits as the GE is misspelled as trustworty factory - without the 'h'. Searching for factory gives a hit and shows the GE, but it's shown as a "closed group". It does give a link to a tar package, which I guess is a linux version of the installed system (I don't have a graphical linux installation available for verifying it)
3. On the admin guide it says: "The installation is realised using the URL update site of the trustworthy factory (https://github.com/TrustworthyFactory/UpdatesiteFactory)." That doesn't work, eclipse doesn't understand it as an update site. The url points to github web pages, not to an update site.
4. Downloading the https://github.com/TrustworthyFactory/UpdatesiteFactory repository as a zip archive and zipping that to your disk gives possibility to get a working update site. 
5. But the unzipped site doesn't seem to define categories and Eclipse Kepler has by default the "Group items by category" selected, which causes the item selection to just say "there are no categorized items" and the user has to realize that he has to unselect the grouping to make the item show. There should be categories defined or the documentation should mention that the "Group items by category"  shoudl be unselected.

**Comment by fredericgithub** [comment]
Good morning, I would be interested too in the answers to the above questions. 
Thanks in advance to the developers for answering.
Best regards,
F.

**Comment by FMotteT** [comment]
Hi all, 

regarding the different elements.
1. The factory is published into the Fiware catalogue. on one download page, you could find the link on the download tab:
https://forge.fiware.org/frs/download.php/1697/eclipse-trustworthyFactory20150930.tar.gz 
2. The GE is now published on the catalogue
3. 4.  Your are right. Your can also download the git project and use it as a local directory.
5. I will change the documentation to specify that
